### PR TITLE
Make Timer run on Android

### PR DESCRIPTION
**Pull request by yurivyatkin**
I have used the directions from https://www.npmjs.com/package/react-native-audioplayer to add the ability for the Timer project to run on Android devices. Tested on a simulator (Genymotion), worked well with the sound playing.

### CODE REVIEW

**Comment by azat-co** [comment]
@rykuehn did you see this? :)

**Comment by rykuehn** [comment]
@yurivyatkin did you have to add the audio file to a res folder? I followed the directions, added the flute sound file to a res/raw file and it worked!

**Comment by rykuehn** [comment]
@yurivyatkin nevermind -- Just saw that  you did add the audio file!

**Comment by azat-co** [comment]
@yurivyatkin thank you! it helped a lot and was merged as part of @rykuehn's PR

**Pull request closed without merging**
